// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQgWusFzfbeJBk1wJJgoXZB9uVyxGy7n0',
    appId: '1:544508288601:web:f2773a294eed4744719b48',
    messagingSenderId: '544508288601',
    projectId: 'safe-bite-59111',
    authDomain: 'safe-bite-59111.firebaseapp.com',
    storageBucket: 'safe-bite-59111.firebasestorage.app',
    measurementId: 'G-M1YG28MBW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOZ433sSnyHZu4D6Osx94UIm4TQQTeVA',
    appId: '1:544508288601:android:c0604c960da47446719b48',
    messagingSenderId: '544508288601',
    projectId: 'safe-bite-59111',
    storageBucket: 'safe-bite-59111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU0oHUMd5RPztiD8PsIirquVWpBLarp6Q',
    appId: '1:544508288601:ios:838addc1416ff152719b48',
    messagingSenderId: '544508288601',
    projectId: 'safe-bite-59111',
    storageBucket: 'safe-bite-59111.firebasestorage.app',
    iosBundleId: 'com.example.safebite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU0oHUMd5RPztiD8PsIirquVWpBLarp6Q',
    appId: '1:544508288601:ios:838addc1416ff152719b48',
    messagingSenderId: '544508288601',
    projectId: 'safe-bite-59111',
    storageBucket: 'safe-bite-59111.firebasestorage.app',
    iosBundleId: 'com.example.safebite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQgWusFzfbeJBk1wJJgoXZB9uVyxGy7n0',
    appId: '1:544508288601:web:4dfcc5ecd1f38402719b48',
    messagingSenderId: '544508288601',
    projectId: 'safe-bite-59111',
    authDomain: 'safe-bite-59111.firebaseapp.com',
    storageBucket: 'safe-bite-59111.firebasestorage.app',
    measurementId: 'G-QQ39D8QJJN',
  );

}